### ISSUE TITLE
Open Source Licensing

### ISSUE THREAD

**Issue by VnUgE** [OpenEEC-Project/SAD806x#2]
Hi, there are some changes/fixes I made to locally a few years ago to get going, and I had an interest in forking this project. Beyond that I have my own CI build system I wish to be able to publish binaries for easier installation for some peeps. I was hoping you may have interest in publishing the code to this repo under an open source license of some sort. I intend to keep everything free and open source as well.

**Comment by thepym** [comment]
Any update, which can help working with this hardware, is welcomed. I have also done some updates too at this moment, but not enough for me to publish a new version. Forking the project is ok for me.

**Comment by VnUgE** [comment]
Doesn't mean you cant commit those changes :)

I appreciate the confirmation, but an open source license would be preferred if that was at all possible. I just want protection for both of us if that was at all possible for you to do

**Comment by thepym** [comment]
Version is now up to date and I have added the License, it should be easier to manage.
Good thing, thanks.
